version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: ${TARGET:-dev}  # Use the TARGET build argument (dev by default)
    container_name: backend
    environment:
      - ENV=${ENV:-development}  # Environment variable for the app
    volumes:
      - ./backend/app:/app  # Mount for dev
    expose:
      - "8000"  # Internal use only
    #ports:
    #  - "8000:8000"  # Optional, expose for local testing in dev only

  frontend:
    build:
      no_cache: true
      context: ./frontend
      target: ${TARGET:-dev}  # Use the TARGET build argument (dev by default)
    container_name: frontend
    environment:
      - ENV=${ENV:-development}
    volumes:
      - ./frontend/app:/app  # Mount for dev
      - /app/node_modules  # Avoid overwriting node_modules
    expose:
      - "3000"  # Internal use only
    #ports:
    #  - "3000:3000"  # Optional, expose for local testing in dev only

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "3000:3000"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
