version: '3.8'
services:
  # db:
  #   #image: jsurf/rpi-mariadb
  #   image: mariadb
  #   container_name: mysql-db
  #   restart: always
  #   environment:
  #     TZ: America/New_York
  #     MYSQL_DATABASE: 'my_db'
  #     MYSQL_ROOT_PASSWORD: 'passw0rd'
  #   ports:
  #     - '3306:3306'
  #   expose:
  #     - '3306'
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
