# backend/Dockerfile
FROM python:3.11-slim

WORKDIR /app
COPY ./app/. /app/
RUN apt update
RUN apt install -y build-essential cargo
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["uvicorn", "app:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]